"""Добавлено поле auth_provider в User

Revision ID: 1350b32e50bc
Revises: c6715e26fedf
Create Date: 2025-05-29 19:58:37.464326

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1350b32e50bc"
down_revision: str | None = "c6715e26fedf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("auth_provider", sa.String(), nullable=False, server_default="email"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
