"""model category updated

Revision ID: 87612c65f1e7
Revises: 495630194611
Create Date: 2025-08-08 02:39:55.592018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87612c65f1e7'
down_revision: Union[str, None] = '495630194611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('duration', sa.Integer(), nullable=False))
    op.drop_column('sprints', 'target_minutes')
    op.drop_column('sprints', 'actual_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('actual_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sprints', sa.Column('target_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sprints', 'duration')
    # ### end Alembic commands ###
