"""updating journal model

Revision ID: aaf21a88baa8
Revises: 758719fbde39
Create Date: 2025-08-28 19:05:49.021503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaf21a88baa8'
down_revision: Union[str, None] = '758719fbde39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'mood')
    op.drop_column('journal_entries', 'updated_at')
    op.drop_column('journal_entries', 'is_archived')
    op.drop_column('journal_entries', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('journal_entries', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('journal_entries', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('journal_entries', sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
