"""set category_id nullable and add ON DELETE SET NULL

Revision ID: f29a9008905f
Revises: 019264187a7d
Create Date: 2025-08-30 00:19:45.201430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29a9008905f'
down_revision: Union[str, None] = '019264187a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sprints_category_id_fkey', 'sprints', type_='foreignkey')
    op.create_foreign_key(None, 'sprints', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.create_foreign_key('sprints_category_id_fkey', 'sprints', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
