"""Test dynamic import

Revision ID: c29dcc7d7207
Revises: 1a6fa1b6c558
Create Date: 2025-02-27 15:39:32.512699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29dcc7d7207'
down_revision: Union[str, None] = '1a6fa1b6c558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
